[package]
name = "dl-sim-rust"
version = "0.1.0"
authors = ["mushymato <wildshinobu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.rusqlite]
version = "0.22.0"
features = ["bundled"]